services:
<<<<<<< HEAD
  student_service:
=======

  demo:
>>>>>>> 8290a4d (fixed docker by reverting to package copying)
    build: .
    image: demo
    container_name: demo
    ports:
<<<<<<< HEAD
     - "8080:8080"
=======
      - "8080:8080"

>>>>>>> 8290a4d (fixed docker by reverting to package copying)
