services:

  dtu-pay:
    build: ./dtu-pay-server
    image: dtu-pay
    container_name: dtu-pay
    environment:
      - RABBITMQ_HOST=rabbitmq
    ports:
     - "8080:8080"
    depends_on:
     rabbitmq:
       condition: service_healthy
    networks:
     - dtu-net

  account-service:
    build: ./account-service
    image: account-service
    environment:
     - RABBITMQ_HOST=rabbitmq
    depends_on:
     rabbitmq:
       condition: service_healthy
    networks:
     - dtu-net

  reporting-service:
    build:
      context: .
      dockerfile: reporting-service/Dockerfile
    image: reporting-service
    environment:
     - RABBITMQ_HOST=rabbitmq
    depends_on:
     rabbitmq:
       condition: service_healthy
    networks:
     - dtu-net

  token-service:
    build:
      context: .
      dockerfile: token-service/Dockerfile
    image: token-service
    environment:
     - RABBITMQ_HOST=rabbitmq
    depends_on:
     rabbitmq:
       condition: service_healthy
    networks:
     - dtu-net

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
     - "5672:5672"
     - "15672:15672"
    healthcheck:
     test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
     interval: 5s
     timeout: 5s
     retries: 12
     start_period: 5s
    networks:
     - dtu-net

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    image: payment-service
    environment:
      - RABBITMQ_HOST=rabbitmq
    container_name: payment-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - dtu-net


networks:
  dtu-net:
    driver: bridge
